spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: discovery-service
eureka:
  client:
    fetchRegistry: 'false'
    registerWithEureka: 'false'
server:
  port: 8761
