
services:

  config-service:
    build:
      context: ./services/config-service
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    healthcheck:
      test: wget --spider --quiet 'http://localhost:8888/actuator/health/' || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  discovery-service:
    build:
      context: ./services/discovery-service
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    healthcheck:
      test: wget --spider --quiet 'http://localhost:8761/actuator/health/' || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s