
services:

  config-service:
    network_mode: host
    build:
      context: ./services/config-service
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s

  discovery-service:
    network_mode: host
    build:
      context: ./services/discovery-service
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      config-service:
        condition: service_healthy

  api-gateway:
    network_mode: host
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      discovery-service:
        condition: service_healthy