spring:
  config:
    import: optional:configserver:http://localhost:8888


token:
  secret: GieJX^>%Pd;Z]#&?kmZY4SRZNlWsjr%JJiH!q9KM~,Zd./[oh*=dus&p_M3Ab#B
  accessExpiration: 7200
  refreshExpiration: 86400